# .goreleaser.yml
# This is an example .goreleaser.yml file with some defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: "KubeBrowse"

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/guac/guac.go
    id: "guac"
    binary: guac
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - templates/**/*
      - certs/generate.sh

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Publish to GitHub Releases
release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "KubeBrowse"
  draft: false
  prerelease: auto
  mode: replace
